# Generated by Django 5.2.1 on 2025-05-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecomponent',
            name='rendered_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
